### ISSUE TITLE
Crash during Synchronization

### ISSUE THREAD

**Issue by ghost** [Onkelsam/VNDBUpdater#2]
Hello.
VNDBUpdator crashes when synchronizer reaches the 25th VN as follows. Log is attached.

> FormatException

> String was not recognized as a valid DateTime.

[Log.txt](https://github.com/Onkelsam/VNDBUpdater/files/1016622/Log.txt)

**Comment by Onkelsam** [comment]
Hi,

sorry that I needed a few days...

I couldn't replicate your issue, but I hope I fixed it by using the Try-Parse method.

Honestly, I should have have used it in the first place; The Parse-method is just a crash waiting to happen.

I uploaded a new release, if you find the time try it please and see if it fixed the issue. Thanks :)

**Comment by ghost** [comment]
Thank you!
Yes, it's working perfectly now. I'm sorry for the late reply. I wanted to organize any problems/suggestions.
1: Some VNDB covers aren't loading even after running update from the context menu(I presume that updates the entries from site?). eg v239 v242 v19770.
2: Having a hotkey to popup fullsize images. eg holding ctrl while hovering over an image will pop up the expanded image. Plus a similiar implementation for covers too.
3: Offline Usage. App cannot start without the internet, presently popping up the login screen.
4: The links in entries are not clickable.
5: No way to filter by title.
6: Redirect relations(relevant games) to relevant existing entry otherwise open in popup.
7: Autoload character description for the active character(character under mouse).
8: Show Loading if something actually exists in the screenshots otherwise text saying none available. 
9: Context menu takes a while to popup.
10: When quick switching occasionally screenshots of the last VN are loaded and only fixed by coming back to the VN after pressing on another entry.
11: Reset window scroller to beginning after changing entries i.e Screenshot and Character tabs.
12: Include screenshot size in adjust image size in settings.

**Comment by Onkelsam** [comment]
Glad its working now.

1: That's a bug I haven't encountered before. I'll have to check it myself before I can confidently say where the issue lies. If you have the time, can please you go into your Resources/Thumbnails folder (e.g. "C:\Program Files (x86)\VNDBUpdater\VNDBUpdaterInstall\Resources\Thumbnails") and look if there is a folder named 239 or 242 or 19770 and check if it contains an image?

2: I'll look into it. Should be doable.

3: Sorry, but currently I don't intend to support offline mode. It probably  wouldn't be that hard to implement, but I mainly created this for myself and I don't require one. But I'll add it to my list.

4: Yeah, I know and I don't think I can change that in the near future. The problem is that the standard RichTextBox from WPF doesn't support dynamic links. I'd probably need to implement a custom behavior and that issue is currently low on my list.

5: Definitely required. I miss that feature too. Will add it in the near future. 

6: What do you mean with "open in popup"?
Currently you can select related vns from the context menu, the ones you have in your list will be selected, the ones not in your list will be opened on vndb. I agree that this is not flashed out at all, e.g. when selecting a related vn that you have, the current tab won't change. I'll add automatic tab change and zoom to selected vn in the future (if that is possible in a reasonable timeframe).

7: I already looked into it, seemed pretty difficult at a first glance and wasn't high on my list. Will try it in the future.

8: I'll look into it. Should be doable.

9: Yeah, but not always (at least in my experience). Maybe its the screenshot/characters loading in the background (downloading the images). That shouldn't block the UI thread, but maybe it gets slowed down. I don't know, but I'll try to make it more responsive.

10: Yeah, but that should only be an issue on initial downloading of the screenshots. The tasks run in parallel the last that finished gets the spotlight :). I'll try to fix it.

11: I'll look into it. Should be doable.

12: That is of course doable. But in the current implementation, it takes the natural screenshot format and makes it as large as possible (so it still fits into the listview). I think that's pretty much as good as it gets.

Thank you very much for your suggestions. For now I'll focus on bug fixing. Additional features will be added after a fairly stable release is done. I'll also only be able to work on it during the weekends and even then I'll mostly focus on "real" work.

There are also a bunch a bugs in the current build:


- Playtime is not always tracked (no idea why...)

- When a tag filter is enabled, vn status cannot be set. Or, more like, it can be set, but it wont be displayed in the view. Only after disabling the filter the view will be updated correctly. No idea how I missed that one before...
